import pandas as pd
import pytest
from unittest.mock import MagicMock
import sys
from AuditoriaProcesso.hierarquia import organograma, busca_organograma


@pytest.fixture
def dados_mock():
    # DataFrames que simulam a planilha real

    auditoria = pd.DataFrame(
        {
            "Setor": [
                "COORDENADORIA DE ALIMENTACAO ESCOLAR",
                "COORDENADORIA DE APLICACAO E VIDA FUNCIONAL",
                "COORDENADORIA DE APOIO AS CAMARAS",
                "COORDENADORIA DE AVALIACAO E MONITORAMENTO EDUCACIONAL",
                "COORDENADORIA DE CONTROLE DE DESPESA E CONFORMIDADE DA FOLHA",
                "COORDENADORIA DE CONVENIOS E PRESTACAO DE CONTAS",
                "COORDENADORIA DE DESENVOLVIMENTO",
                "COORDENADORIA DE EDUCACAO DE JOVENS E ADULTOS",
                "COORDENADORIA DE EDUCACAO EM TEMPO INTEGRAL",
                "COORDENADORIA DE EDUCACAO ESCOLAR INDIGENA",
                "COORDENADORIA DE EDUCACAO ETNICO RACIAL E AMBIENTAL",
                "COORDENADORIA DE EDUCACAO INCLUSIVA",
                "COORDENADORIA DE EDUCACAO INTEGRADA E INOVACAO",
                "COORDENADORIA DE ENSINO FUNDAMENTAL",
                "COORDENADORIA DE ENSINO MEDIO",
                "COORDENADORIA DE EXECUCAO DE OBRAS",
                "COORDENADORIA DE GESTAO DE PESSOAS",
                "COORDENADORIA DE IMPACTO EDUCACIONAL",
                "COORDENADORIA DE MONITORAMENTO DE PESSOAL",
                "COORDENADORIA DE MOVIMENTACAO",
                "COORDENADORIA DE ORCAMENTO",
                "COORDENADORIA DE PATRIMONIO IMOBILIARIO",
                "COORDENADORIA DE PATRIMONIO MOBILIARIO",
                "COORDENADORIA DE PROVIMENTO",
                "COORDENADORIA DE SAUDE E SEGURANCA",
                "COORDENADORIA DE SUPORTE OPERACIONAL",
                "COORDENADORIA FINANCEIRA",
            ],
            "Servidor": [
                "JULIO CESAR BORGES JUNIOR",
                "AGNES RIBEIRO DE SOUZA BRUNO",
                "EDNEIA CRISTINA CASTILHO",
                "GLAUCIA RIBEIRO",
                "FERNANDA BALBUENA FECHTNER COENGA",
                "JOAO GABRIEL RAMOS SILVA",
                "FABIO CESAR PEREIRA JUNIOR",
                "DIVANEA GRANGEIRO ARRUDA",
                "DILMA APARECIDA MOREIRA",
                "AINOA RODRIGUES CHAVES",
                "BENEDITO GONCALO CURVO",
                "HELOANA MARIA TALARICO JACOB",
                "EVANDRO FRANCA",
                "ELENI RICKEN SPADRIZANI",
                "CARLOS MAGNO MARTINS DOS ANJOS",
                "KAROLINE BARROS SANTOS",
                "JACKLINE APARECIDA SILVA",
                "MARIA CLARA MORALES DA CUNHA",
                "AECIO LUIS MOREIRA FERNANDES",
                "RAQUELINA FERREIRA DA SILVA",
                "ANGEL PRISCILLA ALMEIDA GONCALVES",
                "BRUNA GUIMARAES DE SOUZA PIMENTEL",
                "ALESSANDRO LAURO MAGALHAES SERRA",
                "DEUSINA PONCO",
                "ANA KAROLINA DA SILVA CASTRO",
                "AURELINO MONTEIRO CALDAS",
                "ADRIANA SILVA SIQUEIRA",
            ],
            "Matricula": [
                "54321/7",
                "12845/2",
                "98765/10",
                "23456/3",
                "76543/5",
                "34567/1",
                "87654/8",
                "45678/6",
                "65432/9",
                "56789/4",
                "43210/2",
                "67890/7",
                "12345/3",
                "78901/1",
                "23467/5",
                "89012/8",
                "34578/6",
                "90123/9",
                "45689/10",
                "11223/2",
                "66778/4",
                "77889/7",
                "88990/5",
                "99001/3",
                "22334/1",
                "33445/6",
                "44556/8",
            ],
            "Data": [
                "20/01/2026",
                "20/01/2026",
                "20/01/2026",
                "13/01/2026",
                "07/01/2026",
                "13/01/2026",
                "22/01/2026",
                "21/01/2026",
                "19/01/2026",
                "22/01/2026",
                "12/01/2026",
                "07/01/2026",
                "28/01/2026",
                "09/01/2026",
                "17/01/2026",
                "13/01/2026",
                "19/01/2026",
                "19/01/2026",
                "07/01/2026",
                "19/01/2026",
                "06/01/2026",
                "16/01/2026",
                "05/01/2026",
                "20/01/2026",
                "28/01/2026",
                "05/01/2026",
                "12/01/2026",
            ],
            "Quantidade Horas": [
                "08:00:00",
                "06:00:00",
                "08:00:00",
                "06:00:00",
                "08:00:00",
                "06:00:00",
                "06:00:00",
                "08:00:00",
                "12:00:00",
                "08:00:00",
                "08:00:00",
                "06:24:25",
                "06:00:00",
                "06:28:21",
                "06:00:00",
                "08:00:00",
                "08:00:00",
                "08:00:00",
                "03:43:44",
                "08:00:00",
                "08:00:00",
                "08:00:00",
                "08:00:00",
                "04:30:00",
                "04:00:00",
                "08:00:00",
                "08:00:00",
            ],
        }
    )

    return auditoria
